"""FastAPI exception handlers for consistent JSON error responses."""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from fastapi import FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from src.exceptions import ApplicationError

logger = logging.getLogger(__name__)


class ErrorDetail(BaseModel):
    """Structured detail entry for an error response."""

    field: Optional[str] = Field(
        default=None,
        description="Field path associated with the error.",
    )
    message: str = Field(
        ...,
        description="Human-readable description of the detail.",
    )
    type: Optional[str] = Field(
        default=None,
        description="Machine-readable detail type.",
    )


class ErrorBody(BaseModel):
    """Machine-friendly and human-friendly error payload."""

    code: str = Field(..., description="Stable machine-readable code.")
    message: str = Field(..., description="Human-readable error message.")
    details: List[ErrorDetail] = Field(
        default_factory=list,
        description="Additional structured error details.",
    )


class ErrorResponse(BaseModel):
    """Top-level API error response envelope."""

    error: ErrorBody
    detail: str = Field(
        ...,
        description="Backward-compatible summary of the error.",
    )


def _build_error_response(
    *,
    status_code: int,
    code: str,
    message: str,
    details: Optional[List[Dict[str, Any]]] = None,
) -> JSONResponse:
    """Create a JSONResponse with the standard error envelope.

    Args:
        status_code: HTTP status code to return.
        code: Stable machine-readable error code.
        message: Human-readable error summary.
        details: Optional structured detail items.

    Returns:
        JSONResponse: Serialized error payload.
    """
    response = ErrorResponse(
        error=ErrorBody(
            code=code,
            message=message,
            details=[ErrorDetail(**detail) for detail in details or []],
        ),
        detail=message,
    )
    return JSONResponse(
        status_code=status_code,
        content=response.model_dump(mode="json"),
    )


def _format_validation_details(
    exc: RequestValidationError,
) -> List[Dict[str, Any]]:
    """Convert FastAPI validation errors into the standard format.

    Args:
        exc: FastAPI validation exception.

    Returns:
        List[Dict[str, Any]]: Structured validation detail entries.
    """
    details: List[Dict[str, Any]] = []
    for error in exc.errors():
        location = [str(part) for part in error.get("loc", [])]
        field = ".".join(location) if location else None
        details.append(
            {
                "field": field,
                "message": error.get("msg", "Invalid request."),
                "type": error.get("type"),
            }
        )
    return details


async def handle_application_error(
    request: Request,
    exc: ApplicationError,
) -> JSONResponse:
    """Handle expected application errors.

    Args:
        request: Incoming HTTP request.
        exc: Application-specific exception.

    Returns:
        JSONResponse: Structured error payload.
    """
    logger.error(
        "Application error on %s %s: %s",
        request.method,
        request.url.path,
        exc.message,
        extra={"error_code": exc.error_code},
        exc_info=True,
    )
    return _build_error_response(
        status_code=exc.status_code,
        code=exc.error_code,
        message=exc.message,
        details=exc.details,
    )


async def handle_http_exception(
    request: Request,
    exc: HTTPException,
) -> JSONResponse:
    """Handle FastAPI HTTP exceptions consistently.

    Args:
        request: Incoming HTTP request.
        exc: HTTP exception raised by FastAPI or route code.

    Returns:
        JSONResponse: Structured error payload.
    """
    message = (
        exc.detail if isinstance(exc.detail, str) else "Request failed."
    )
    logger.error(
        "HTTP error on %s %s: %s",
        request.method,
        request.url.path,
        message,
        exc_info=True,
    )
    return _build_error_response(
        status_code=exc.status_code,
        code="http_error",
        message=message,
    )


async def handle_request_validation_error(
    request: Request,
    exc: RequestValidationError,
) -> JSONResponse:
    """Handle request validation failures.

    Args:
        request: Incoming HTTP request.
        exc: Validation exception generated by FastAPI.

    Returns:
        JSONResponse: Structured validation error payload.
    """
    logger.warning(
        "Validation error on %s %s",
        request.method,
        request.url.path,
        extra={"validation_errors": exc.errors()},
    )
    return _build_error_response(
        status_code=422,
        code="validation_error",
        message="Request validation failed.",
        details=_format_validation_details(exc),
    )


async def handle_unexpected_exception(
    request: Request,
    exc: Exception,
) -> JSONResponse:
    """Handle unexpected server exceptions.

    Args:
        request: Incoming HTTP request.
        exc: Unhandled exception.

    Returns:
        JSONResponse: Structured internal error payload.
    """
    logger.error(
        "Unhandled error on %s %s",
        request.method,
        request.url.path,
        exc_info=True,
    )
    return _build_error_response(
        status_code=500,
        code="internal_server_error",
        message="An unexpected server error occurred.",
    )


def register_exception_handlers(app: FastAPI) -> None:
    """Register application-wide exception handlers.

    Args:
        app: FastAPI application instance.
    """
    app.add_exception_handler(ApplicationError, handle_application_error)
    app.add_exception_handler(HTTPException, handle_http_exception)
    app.add_exception_handler(
        RequestValidationError,
        handle_request_validation_error,
    )
    app.add_exception_handler(Exception, handle_unexpected_exception)
